"""
PowerPoint Writer Agent
=======================

Converts markdown report content to PowerPoint using the Sweetspot template.

This agent is responsible for the final output formatting of the Discovery Solution report.

Template Layouts (Sweetspot):
- 0: Blank_Slide - For title slides
- 1: content_slide - For bullet point content
- 2: chapter_slide - For section headers
- 3: text_left_slide - Text on left with image area
- 4: text_right_slide - Text on right with image area
"""

import os
import re
import logging
from pathlib import Path
from typing import Optional, List, Dict, Any
from datetime import datetime

from agno.agent import Agent
from agno.models.anthropic import Claude

from db import get_postgres_db

# ============================================================================
# Logging Setup
# ============================================================================
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("PowerPointWriter")

# ============================================================================
# Setup
# ============================================================================
agent_db = get_postgres_db(contents_table="powerpoint_writer_contents")

# Template path - use the fixed Sweetspot template
TEMPLATE_DIR = Path(__file__).parent.parent / "templates"
TEMPLATE_PATH = os.getenv(
    "PPTX_TEMPLATE_PATH",
    str(TEMPLATE_DIR / "sweetspot_template.pptx")
)

# Output directory
OUTPUT_DIR = Path(os.getenv("OUTPUT_DIR", "./output"))

# ============================================================================
# Agent Instructions
# ============================================================================
instructions = """\
You are a PowerPoint formatting specialist for consulting deliverables.

## Your Task

Help structure content for PowerPoint slides. Given markdown content, you:
1. Suggest optimal slide breakdown
2. Identify key points for each slide
3. Recommend which slide layout to use (title, content, chapter, etc.)

## Sweetspot Slide Layouts Available

1. **Blank Slide** (0) - For title/cover slides
2. **Content Slide** (1) - For detailed bullet points
3. **Chapter Slide** (2) - For section dividers/headers
4. **Text Left Slide** (3) - Content with image area on right
5. **Text Right Slide** (4) - Content with image area on left

## Guidelines

- Keep bullet points concise (max 7 words per line ideal)
- Max 6 bullet points per slide
- Use Chapter slides between major sections
- Important stats/numbers get their own highlight slide
- Follow Sweetspot branding and styling
"""

# ============================================================================
# Create Agent
# ============================================================================
powerpoint_writer_agent = Agent(
    id="powerpoint-writer",
    name="PowerPoint Writer",
    model=Claude(id="claude-sonnet-4-20250514"),
    db=agent_db,
    instructions=instructions,
    add_datetime_to_context=True,
    markdown=True,
)


# ============================================================================
# Slide Data Structures
# ============================================================================
class SlideContent:
    """Represents content for a single slide."""

    LAYOUT_BLANK = 0
    LAYOUT_CONTENT = 1
    LAYOUT_CHAPTER = 2
    LAYOUT_TEXT_LEFT = 3
    LAYOUT_TEXT_RIGHT = 4

    def __init__(
        self,
        layout: int,
        title: str,
        content: List[str] = None,
        notes: str = "",
    ):
        self.layout = layout
        self.title = title
        self.content = content or []
        self.notes = notes

    def to_dict(self) -> Dict[str, Any]:
        return {
            "layout": self.layout,
            "title": self.title,
            "content": self.content,
            "notes": self.notes,
        }


# ============================================================================
# Markdown to Slides Conversion
# ============================================================================
def parse_markdown_to_slides(markdown_content: str, customer_name: str = "Client") -> List[SlideContent]:
    """
    Parse markdown content into slide structures using Sweetspot layouts.

    Args:
        markdown_content: The markdown report content
        customer_name: Customer name for title slide

    Returns:
        List of SlideContent objects
    """
    slides = []

    # Title slide (blank layout)
    slides.append(SlideContent(
        layout=SlideContent.LAYOUT_BLANK,
        title="Discovery Solution Report",
        content=[customer_name, datetime.now().strftime("%B %Y")],
        notes="Generated by AgentOS Discovery Team"
    ))

    # Parse sections (H3 headings)
    sections = re.split(r'^### ', markdown_content, flags=re.MULTILINE)

    for section in sections[1:]:  # Skip content before first H3
        lines = section.strip().split('\n')
        if not lines:
            continue

        title = lines[0].strip()
        body_lines = lines[1:]

        # Chapter slide for section header
        slides.append(SlideContent(
            layout=SlideContent.LAYOUT_CHAPTER,
            title=title,
        ))

        # Collect bullet points (skip evidence sources and metadata)
        bullets = []
        for line in body_lines:
            line = line.strip()
            # Skip evidence footer and metadata lines
            if any(skip in line for skip in ['**Evidence', '[Intake', '**Open Questions', '---']):
                continue
            if line.startswith('- ') or line.startswith('* '):
                bullet_text = line[2:].strip()
                # Truncate long bullets
                if len(bullet_text) > 100:
                    bullet_text = bullet_text[:97] + "..."
                if bullet_text:
                    bullets.append(bullet_text)

        # Split bullets into slides of max 6 each
        bullet_chunks = [bullets[i:i+6] for i in range(0, len(bullets), 6)]

        for chunk_idx, chunk in enumerate(bullet_chunks):
            if not chunk:
                continue

            slide_title = title if chunk_idx == 0 else f"{title} (cont.)"
            slides.append(SlideContent(
                layout=SlideContent.LAYOUT_CONTENT,
                title=slide_title,
                content=chunk,
            ))

    return slides


def create_powerpoint(
    slides: List[SlideContent],
    output_path: str,
    template_path: str = None,
    customer_name: str = "Client",
) -> bool:
    """
    Create a PowerPoint file from slide content using Sweetspot template.

    Args:
        slides: List of SlideContent objects
        output_path: Where to save the .pptx file
        template_path: Path to Sweetspot .pptx template
        customer_name: Customer name for title slide

    Returns:
        True if successful, False otherwise
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError:
        logger.error("python-pptx not installed. Run: pip install python-pptx")
        return False

    template = template_path or TEMPLATE_PATH

    # Load template or create blank
    if template and Path(template).exists():
        logger.info(f"Loading Sweetspot template: {template}")
        try:
            prs = Presentation(template)

            # Clear existing slides from template
            while len(prs.slides) > 0:
                rId = prs.slides._sldIdLst[0].rId
                prs.part.drop_rel(rId)
                del prs.slides._sldIdLst[0]

        except Exception as e:
            logger.warning(f"Could not load template: {e}, using blank")
            prs = Presentation()
    else:
        logger.warning(f"Template not found at {template}, using blank presentation")
        prs = Presentation()

    # Check if we have Sweetspot layouts
    has_sweetspot_layouts = len(prs.slide_layouts) >= 5

    for slide_content in slides:
        layout_idx = slide_content.layout

        # Ensure layout index is valid
        if layout_idx >= len(prs.slide_layouts):
            layout_idx = 0

        layout = prs.slide_layouts[layout_idx]
        slide = prs.slides.add_slide(layout)

        # Handle different layout types
        if slide_content.layout == SlideContent.LAYOUT_BLANK:
            # Title slide - add text box
            txBox = slide.shapes.add_textbox(Inches(0.5), Inches(2), Inches(12), Inches(3))
            tf = txBox.text_frame

            p = tf.paragraphs[0]
            p.text = slide_content.title
            p.font.size = Pt(44)
            p.font.bold = True
            p.font.name = 'Arial'

            for i, line in enumerate(slide_content.content):
                p = tf.add_paragraph()
                p.text = line
                p.font.size = Pt(36) if i == 0 else Pt(20)
                p.font.name = 'Arial'

        elif slide_content.layout == SlideContent.LAYOUT_CHAPTER:
            # Chapter/section header slide
            if slide.shapes.title:
                slide.shapes.title.text = slide_content.title
            else:
                txBox = slide.shapes.add_textbox(Inches(0.5), Inches(2.5), Inches(12), Inches(2))
                tf = txBox.text_frame
                p = tf.paragraphs[0]
                p.text = slide_content.title
                p.font.size = Pt(40)
                p.font.bold = True
                p.font.name = 'Arial'

        else:
            # Content slides (LAYOUT_CONTENT, TEXT_LEFT, TEXT_RIGHT)
            # Set title
            if slide.shapes.title:
                slide.shapes.title.text = slide_content.title

            # Find content placeholder or add textbox
            content_shape = None
            for shape in slide.shapes:
                if shape.has_text_frame and shape != slide.shapes.title:
                    content_shape = shape
                    break

            if content_shape and slide_content.content:
                tf = content_shape.text_frame
                tf.clear()
                for i, bullet in enumerate(slide_content.content):
                    if i == 0:
                        p = tf.paragraphs[0]
                    else:
                        p = tf.add_paragraph()
                    p.text = bullet
                    p.font.size = Pt(18)
                    p.font.name = 'Arial'
                    p.level = 0
            elif slide_content.content:
                # Add textbox for content
                txBox = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(12), Inches(5))
                tf = txBox.text_frame
                for i, bullet in enumerate(slide_content.content):
                    if i == 0:
                        p = tf.paragraphs[0]
                    else:
                        p = tf.add_paragraph()
                    p.text = "• " + bullet
                    p.font.size = Pt(18)
                    p.font.name = 'Arial'

        # Add notes
        if slide_content.notes:
            notes_slide = slide.notes_slide
            notes_slide.notes_text_frame.text = slide_content.notes

    # Ensure output directory exists
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Save
    prs.save(str(output_file))
    logger.info(f"PowerPoint saved: {output_file} ({len(prs.slides)} slides)")

    return True


def generate_powerpoint_from_markdown(
    markdown_content: str,
    customer_name: str,
    output_filename: str = None,
    template_path: str = None,
) -> Dict[str, Any]:
    """
    Main function to generate PowerPoint from markdown using Sweetspot template.

    Args:
        markdown_content: The complete markdown report
        customer_name: Customer name for title slide
        output_filename: Optional custom filename
        template_path: Optional custom template path

    Returns:
        Dict with success status, path, and slide count
    """
    result = {
        "success": False,
        "output_path": None,
        "slide_count": 0,
        "error": None,
    }

    try:
        # Parse markdown to slides
        slides = parse_markdown_to_slides(markdown_content, customer_name)
        result["slide_count"] = len(slides)

        # Generate output filename
        if not output_filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_name = re.sub(r'[^a-zA-Z0-9]', '_', customer_name)
            output_filename = f"discover_solution_{safe_name}_{timestamp}.pptx"

        output_path = OUTPUT_DIR / output_filename

        # Create PowerPoint with Sweetspot template
        success = create_powerpoint(
            slides=slides,
            output_path=str(output_path),
            template_path=template_path or TEMPLATE_PATH,
            customer_name=customer_name,
        )

        if success:
            result["success"] = True
            result["output_path"] = str(output_path)
            logger.info(f"Generated {len(slides)} slides -> {output_path}")
        else:
            result["error"] = "Failed to create PowerPoint file"

    except Exception as e:
        result["error"] = str(e)
        logger.error(f"PowerPoint generation failed: {e}")

    return result


def suggest_slide_structure(markdown_content: str) -> str:
    """
    Use the agent to suggest optimal slide structure.

    Args:
        markdown_content: The markdown report content

    Returns:
        Agent's suggestions as string
    """
    prompt = f"""
Analyze this markdown content and suggest the optimal PowerPoint slide structure
using Sweetspot template layouts.

**Content:**
```markdown
{markdown_content[:3000]}
```

Available Sweetspot layouts:
- Blank Slide (0): Title/cover
- Content Slide (1): Bullet points
- Chapter Slide (2): Section headers
- Text Left (3): Content + image area
- Text Right (4): Image area + content

Provide:
1. Recommended number of slides
2. Slide-by-slide breakdown with layout type and content
3. Any content that should be split across multiple slides
"""

    response = powerpoint_writer_agent.run(prompt)
    return response.content if hasattr(response, 'content') else str(response)


# ============================================================================
# Template Utilities
# ============================================================================
def ensure_template_available() -> bool:
    """
    Ensure the Sweetspot template is available and valid.

    Returns:
        True if template is ready, False otherwise
    """
    template_path = Path(TEMPLATE_PATH)

    if not template_path.exists():
        logger.warning(f"Template not found: {template_path}")
        return False

    try:
        from pptx import Presentation
        prs = Presentation(str(template_path))
        logger.info(f"Template validated: {len(prs.slide_layouts)} layouts available")
        return True
    except Exception as e:
        logger.error(f"Template validation failed: {e}")
        return False


def list_template_layouts() -> List[str]:
    """
    List available layouts in the Sweetspot template.

    Returns:
        List of layout names
    """
    try:
        from pptx import Presentation
        prs = Presentation(TEMPLATE_PATH)
        return [layout.name for layout in prs.slide_layouts]
    except Exception as e:
        logger.error(f"Could not read template layouts: {e}")
        return []


# ============================================================================
# Main
# ============================================================================
if __name__ == "__main__":
    print("PowerPoint Writer - Sweetspot Template")
    print("=" * 50)

    # Check template
    print(f"\nTemplate path: {TEMPLATE_PATH}")
    print(f"Template exists: {Path(TEMPLATE_PATH).exists()}")

    layouts = list_template_layouts()
    if layouts:
        print(f"\nAvailable layouts:")
        for i, name in enumerate(layouts):
            print(f"  {i}: {name}")

    # Test with sample content
    test_markdown = """
### Executive Summary

- Cloud-based roll asset management platform
- Serves industrial customers tracking roller lifecycle
- Built on modern cloud-native architecture

### Technical Architecture

- Web portal: Vue.js with TypeScript
- Mobile: Kotlin Multiplatform
- Backend: Kotlin + Spring Boot
- Database: Azure Cosmos DB

### Recommendations

- Implement CI/CD pipeline improvements
- Add comprehensive API documentation
- Consider containerization strategy
"""

    print("\n" + "=" * 50)
    print("Testing PowerPoint generation...")

    result = generate_powerpoint_from_markdown(
        markdown_content=test_markdown,
        customer_name="Test Customer",
    )

    if result["success"]:
        print(f"\n✅ Success!")
        print(f"   Slides: {result['slide_count']}")
        print(f"   Output: {result['output_path']}")
    else:
        print(f"\n❌ Failed: {result['error']}")
